-- UB Korea dashboard / Supabase integration setup
-- Run once in Supabase Dashboard > SQL Editor.
-- This script does not recreate or replace existing inventory/business tables.

create table if not exists public.dashboard_import_unmatched (
  id bigint generated by default as identity primary key,
  source_kind text not null,
  source_file text not null default '',
  row_key text not null,
  source_payload jsonb not null,
  reason text not null,
  status text not null default 'pending'
    check (status in ('pending', 'mapped', 'ignored')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  seen_count integer not null default 1,
  unique (source_kind, source_file, row_key)
);

create table if not exists public.dashboard_import_runs (
  run_key text primary key,
  source_kind text not null,
  source_file text not null default '',
  status text not null check (status in ('success', 'failed', 'partial')),
  counts jsonb not null default '{}'::jsonb,
  error text,
  created_at timestamptz not null default now()
);

alter table public.dashboard_import_unmatched enable row level security;
alter table public.dashboard_import_runs enable row level security;

revoke all on table public.dashboard_import_unmatched from public, anon, authenticated;
revoke all on table public.dashboard_import_runs from public, anon, authenticated;
grant select, insert, update on table public.dashboard_import_unmatched to service_role;
grant select, insert, update on table public.dashboard_import_runs to service_role;
grant usage, select on sequence public.dashboard_import_unmatched_id_seq to service_role;

-- Returns live metadata only. It never reads business rows.
-- SECURITY INVOKER keeps the caller's permissions and does not bypass RLS.
create or replace function public.dashboard_schema(
  p_schemas text[] default array['public', 'analytics']::text[]
)
returns jsonb
language sql
stable
security invoker
set search_path = pg_catalog, public
as $$
  with relations as (
    select
      c.oid,
      n.nspname as schema_name,
      c.relname as relation_name,
      case c.relkind
        when 'p' then 'partitioned_table'
        when 'r' then 'table'
        when 'v' then 'view'
        when 'm' then 'materialized_view'
        else c.relkind::text
      end as relation_type,
      pn.nspname as parent_schema,
      pc.relname as parent_name
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    left join pg_inherits i on i.inhrelid = c.oid
    left join pg_class pc on pc.oid = i.inhparent
    left join pg_namespace pn on pn.oid = pc.relnamespace
    where n.nspname = any(p_schemas)
      and c.relkind in ('r', 'p', 'v', 'm')
  )
  select jsonb_build_object(
    'generated_at', now(),
    'schemas', to_jsonb(p_schemas),
    'tables', coalesce(jsonb_agg(
      jsonb_build_object(
        'schema', r.schema_name,
        'name', r.relation_name,
        'type', r.relation_type,
        'parent_schema', r.parent_schema,
        'parent_name', r.parent_name,
        'columns', coalesce((
          select jsonb_agg(
            jsonb_build_object(
              'name', a.attname,
              'data_type', format_type(a.atttypid, a.atttypmod),
              'nullable', not a.attnotnull,
              'default', pg_get_expr(ad.adbin, ad.adrelid),
              'ordinal', a.attnum,
              'pk', exists (
                select 1 from pg_constraint pk
                where pk.conrelid = r.oid
                  and pk.contype = 'p'
                  and a.attnum = any(pk.conkey)
              )
            ) order by a.attnum
          )
          from pg_attribute a
          left join pg_attrdef ad on ad.adrelid = a.attrelid and ad.adnum = a.attnum
          where a.attrelid = r.oid and a.attnum > 0 and not a.attisdropped
        ), '[]'::jsonb),
        'primary_key', coalesce((
          select jsonb_agg(a.attname order by key_col.ordinality)
          from pg_constraint con
          cross join lateral unnest(con.conkey) with ordinality as key_col(attnum, ordinality)
          join pg_attribute a on a.attrelid = con.conrelid and a.attnum = key_col.attnum
          where con.conrelid = r.oid and con.contype = 'p'
        ), '[]'::jsonb),
        'unique_constraints', coalesce((
          select jsonb_agg(jsonb_build_object('name', unique_rows.conname, 'columns', unique_rows.columns))
          from (
            select con.conname,
              jsonb_agg(a.attname order by key_col.ordinality) as columns
            from pg_constraint con
            cross join lateral unnest(con.conkey) with ordinality as key_col(attnum, ordinality)
            join pg_attribute a on a.attrelid = con.conrelid and a.attnum = key_col.attnum
            where con.conrelid = r.oid and con.contype = 'u'
            group by con.conname
          ) unique_rows
        ), '[]'::jsonb),
        'foreign_keys', coalesce((
          select jsonb_agg(jsonb_build_object(
            'name', fk_rows.conname,
            'columns', fk_rows.local_columns,
            'foreign_schema', fk_rows.foreign_schema,
            'foreign_table', fk_rows.foreign_table,
            'foreign_columns', fk_rows.foreign_columns
          ))
          from (
            select con.conname,
              fn.nspname as foreign_schema,
              fc.relname as foreign_table,
              jsonb_agg(la.attname order by local_key.ordinality) as local_columns,
              jsonb_agg(fa.attname order by local_key.ordinality) as foreign_columns
            from pg_constraint con
            cross join lateral unnest(con.conkey) with ordinality as local_key(attnum, ordinality)
            join lateral unnest(con.confkey) with ordinality as foreign_key(attnum, ordinality)
              on foreign_key.ordinality = local_key.ordinality
            join pg_attribute la on la.attrelid = con.conrelid and la.attnum = local_key.attnum
            join pg_attribute fa on fa.attrelid = con.confrelid and fa.attnum = foreign_key.attnum
            join pg_class fc on fc.oid = con.confrelid
            join pg_namespace fn on fn.oid = fc.relnamespace
            where con.conrelid = r.oid and con.contype = 'f'
            group by con.conname, fn.nspname, fc.relname
          ) fk_rows
        ), '[]'::jsonb)
      ) order by r.schema_name, r.relation_name
    ), '[]'::jsonb)
  )
  from relations r;
$$;

revoke all on function public.dashboard_schema(text[]) from public, anon, authenticated;
grant execute on function public.dashboard_schema(text[]) to service_role;

comment on function public.dashboard_schema(text[]) is
  'Live table, column, primary-key, foreign-key and partition metadata for the local UB Korea dashboard.';

notify pgrst, 'reload schema';
